### ISSUE TITLE
sync-from-downstream job tracebacks now

### ISSUE THREAD

**Issue by TomasTomecek** [packit/packit-service#119]
```
[2019-09-09 12:52:14,411: INFO/ForkPoolWorker-1] Dist-git commit event, topic: org.fedoraproject.prod.git.receive                                                            
[2019-09-09 12:52:14,411: INFO/ForkPoolWorker-1] New commits added to dist-git repo modules/stratis, branch 1.                                                               
[2019-09-09 12:52:14,411: INFO/ForkPoolWorker-1] msg_id = 2019-e70c028b-9202-4d44-86b0-d79e58aefdf1                                                                          
[2019-09-09 12:52:14,414: INFO/MainProcess] Received task: task.steve_jobs.process_message[83913d5d-f8b7-4118-8a5e-a209ce7a2482]                                             
[2019-09-09 12:52:14,421: INFO/MainProcess] Received task: task.steve_jobs.process_message[c810d2ad-28fa-402e-9451-d986084d2a78]                                             
[2019-09-09 12:52:14,423: INFO/MainProcess] Received task: task.steve_jobs.process_message[abf527f4-69fc-40d8-b7d2-1e5c158c6b3b]                                             
[2019-09-09 12:52:14,424: INFO/MainProcess] Received task: task.steve_jobs.process_message[30897601-f0cb-4684-81f4-8b4768e9f82d]                                             
[2019-09-09 12:52:14,425: ERROR/ForkPoolWorker-1] Task task.steve_jobs.process_message[148b699f-9382-4c1c-9194-e927f01992de] raised unexpected: AttributeError("'PagureServi$
e' object has no attribute 'github_app_id'")                                                                                                                                 
Traceback (most recent call last):                                                                                                                                           
  File "/usr/lib/python3.7/site-packages/celery/app/trace.py", line 382, in trace_task                                                                                       
    R = retval = fun(*args, **kwargs)                                                                                                                                        
  File "/usr/lib/python3.7/site-packages/celery/app/trace.py", line 641, in __protected_call__                                                                               
    return self.run(*args, **kwargs)                                                                                                                                         
  File "/usr/local/lib/python3.7/site-packages/packit_service/worker/tasks.py", line 42, in process_message                                                                  
    return SteveJobs().process_message(event=event, topic=topic)                                                                                                             
  File "/usr/local/lib/python3.7/site-packages/packit_service/worker/jobs.py", line 204, in process_message                                                                  
    if self._is_private(event_object.get_project()):                                                                                                                         
  File "/usr/local/lib/python3.7/site-packages/packit_service/worker/jobs.py", line 79, in _is_private                                                                       
    return github_project.github_repo.private                                                                                                                                
  File "/usr/local/lib/python3.7/site-packages/ogr/services/github.py", line 240, in github_repo                                                                             
    self._github_repo = self.github_instance.get_repo(                                                                                                                       
  File "/usr/local/lib/python3.7/site-packages/ogr/services/github.py", line 223, in github_instance
    if self.service.github_app_id and self.service.github_app_private_key:
AttributeError: 'PagureService' object has no attribute 'github_app_id'
```

**Comment by lachmanfrantisek** [comment]
It looks like we are calling `_is_private` on `PagureProject` (distgit project).

https://github.com/packit-service/packit-service/blob/master/packit_service/worker/jobs.py#L77

**Comment by lachmanfrantisek** [comment]
Especially here:
https://github.com/packit-service/packit-service/blob/master/packit_service/service/events.py#L361

The `DistGitEvent.get_project` returns `PagureProject`:

**Comment by TomasTomecek** [comment]
Is this fixed now?

**Comment by TomasTomecek** [comment]
AI: we need to be able to push to github repos authenticated as GitHub app (release-bot can do this)

Other issues have higher prio than this one for devconf.

**Comment by TomasTomecek** [comment]
Okay, we don't even consume the messages now: https://apps.fedoraproject.org/datagrepper/id?id=2020-fb0c5f8b-b786-4d50-a64c-4faa92e11293&is_raw=true&size=extra-large

nothing happened in packit after I did this

**Comment by TomasTomecek** [comment]
I think the action here is to remove code and docs for this.

With the new source-git workflow we will need to address this somewhat and I'd vote to write code for this from scratch.

**Comment by lachmanfrantisek** [comment]
I think the core problem was solved (probably in https://github.com/packit/packit-service/pull/601 and in https://github.com/packit/ogr/pull/328), but we can still do better in OGR: https://github.com/packit/ogr/issues/330
