### ISSUE TITLE
Service pod errors out on Fedora 35

### ISSUE THREAD

**Issue by lbarcziova** [packit/packit-service#1274]
```
Exception occurred processing WSGI script '/usr/share/packit/packit.wsgi'.
Traceback (most recent call last):
[Tue Nov 09 13:09:12.867761 2021] [wsgi:error]   File "/usr/share/packit/packit.wsgi", line 1, in <module>
[Tue Nov 09 13:09:12.867766 2021] [wsgi:error]    from packit_service.service.app import application
[Tue Nov 09 13:09:12.867772 2021] [wsgi:error]   File "/usr/local/lib/python3.10/site-packages/packit_service/service/app.py", line 14, in <module>
[Tue Nov 09 13:09:12.867776 2021] [wsgi:error]     from packit_service.log_versions import log_service_versions
[Tue Nov 09 13:09:12.867781 2021] [wsgi:error]   File "/usr/local/lib/python3.10/site-packages/packit_service/log_versions.py", line 10, in <module>
[Tue Nov 09 13:09:12.867785 2021] [wsgi:error]    from flask_restx import __version__ as restx_version
[Tue Nov 09 13:09:12.867790 2021] [wsgi:error]   File "/usr/lib/python3.10/site-packages/flask_restx/__init__.py", line 4, in <module>
[Tue Nov 09 13:09:12.867792 2021] [wsgi:error]     from . import fields, reqparse, apidoc, inputs, cors
[Tue Nov 09 13:09:12.867795 2021] [wsgi:error]   File "/usr/lib/python3.10/site-packages/flask_restx/reqparse.py", line 19, in <module>
[Tue Nov 09 13:09:12.867798 2021] [wsgi:error]     from .model import Model
[Tue Nov 09 13:09:12.867801 2021] [wsgi:error]  File "/usr/lib/python3.10/site-packages/flask_restx/model.py", line 21, in <module>
[Tue Nov 09 13:09:12.867804 2021] [wsgi:error]     from jsonschema import Draft4Validator
[Tue Nov 09 13:09:12.867807 2021] [wsgi:error]  File "/usr/lib/python3.10/site-packages/jsonschema/__init__.py", line 21, in <module>
[Tue Nov 09 13:09:12.867811 2021] [wsgi:error]    from jsonschema._types import TypeChecker
[Tue Nov 09 13:09:12.867815 2021] [wsgi:error]  File "/usr/lib/python3.10/site-packages/jsonschema/_types.py", line 168, in <module>
[Tue Nov 09 13:09:12.867818 2021] [wsgi:error]    draft3_type_checker = TypeChecker(
[Tue Nov 09 13:09:12.867829 2021] [wsgi:error]  TypeError: TypeChecker() takes no arguments
```

May be related to [bumping Fedora version in the base image](https://github.com/packit/deployment/pull/276).

**Comment by TomasTomecek** [comment]
so the libraries are incompatible on f35? :/

**Comment by csomh** [comment]
So this is weird: I'm not able to reproduce this error in any way, neither from an interactive Python shell, nor by running some Python scripts.

From the error, and looking at the code in `jsonschema._types` it seems as if the `@attr.s` decorator on the `TypeChecker` class defined there would be ignored (or not executed), and so the class constructor is considered to be without any arguments, so the error is raised when `draft3_type_checker` is declared later on.

I'll revert the base image to Fedora Linux 34 until I manage to pin down why this error is happening.

**Comment by csomh** [comment]
The next experiment to do here is to write a simple flask app, which has `from jsonschema._types import TypeChecker` in it, and it's served with `mod_wsgi`. In case a query to this app does not trigger the error, add `flask_restx` to the stack.

```
bash-5.1# rpm -q python3-mod_wsgi
python3-mod_wsgi-4.9.0-1.fc35.x86_64
bash-5.1# rpm -q python3-jsonschema
python3-jsonschema-3.2.0-12.fc35.noarch
bash-5.1# rpm -q python3-attrs
python3-attrs-21.2.0-4.fc35.noarch
bash-5.1# rpm -q python3-flask
python3-flask-2.0.1-2.fc35.noarch
bash-5.1# rpm -q python3-flask_restx
package python3-flask_restx is not installed
bash-5.1# pip show flask_restx
Name: flask-restx
Version: 0.5.1
Summary: Fully featured framework for fast, easy and documented API development with Flask
Home-page: https://github.com/python-restx/flask-restx
Author: python-restx Authors
Author-email:
License: BSD-3-Clause
Location: /usr/lib/python3.10/site-packages
Requires: jsonschema, Flask, werkzeug, pytz, six, aniso8601
Required-by:
bash-5.1# python3 --version
Python 3.10.0
bash-5.1# cat /etc/fedora-release
Fedora release 35 (Thirty Five)
```

**Comment by csomh** [comment]
GrahamDumpleton/mod_wsgi#729

**Comment by csomh** [comment]
Based on the discussion on the mod_wsgi issue above:
- This issue doesn't seem to be mod_wsgi related as I originally assumed.
- Using `mod_wsgi-express` to start the server (instead of calling `httpd` directly) makes the issue go away on Fedora 35. As I've learnt `mod_wsgi-express` _"provides a much better default configuration if running mod_wsgi inside of a container"_.

So the next step is to change the service container image to use `mod_wsgi-express` to start the server process.
