### ISSUE TITLE
allowlist.py approve results in KeyError: 'gray'

### ISSUE THREAD

**Issue by jpopelka** [packit/packit-service#1313]
```
$ oc exec packit-worker-0 allowlist.py approve https://github.com/namespace

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/click/termui.py", line 498, in style
    bits.append("\033[{}m".format(_ansi_colors[fg]))
KeyError: 'gray'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/allowlist.py", line 154, in <module>
    cli()
  File "/usr/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1257, in invoke
    sub_ctx = cmd.make_context(cmd_name, args, parent=ctx)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 700, in make_context
    self.parse_args(ctx, args)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1048, in parse_args
    value, args = param.handle_parse_result(ctx, opts, args)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1623, in handle_parse_result
    value = self.full_process_value(ctx, value)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1589, in full_process_value
    value = self.process_value(ctx, value)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1579, in process_value
    return self.type_cast_value(ctx, value)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1568, in type_cast_value
    return _convert(value, (self.nargs != 1) + bool(self.multiple))
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1565, in _convert
    return self.type(value, self, ctx)
  File "/usr/lib/python3.9/site-packages/click/types.py", line 46, in __call__
    return self.convert(value, param, ctx)
  File "/usr/bin/allowlist.py", line 58, in convert
    click.secho("Protocol ignored when allowlisting.", fg="gray")
  File "/usr/lib/python3.9/site-packages/click/termui.py", line 547, in secho
    message = style(message, **styles)
  File "/usr/lib/python3.9/site-packages/click/termui.py", line 500, in style
    raise TypeError("Unknown color '{}'".format(fg))
TypeError: Unknown color 'gray'
command terminated with exit code 1
```

The same when I try via Terminal on Openshift console.

EDIT: And btw, the [README](https://github.com/packit/packit-service/blob/main/files/scripts/README.md) needs some update as well as the `allowlist.py` is no longer in `/src/files/scripts/`

**Comment by jpopelka** [comment]
Ok, so the `click.secho()` is not called when I remove the `https://`
```
sh-5.1$ allowlist.py approve github.com/mpeters
Are you manipulating with a namespace ‹github.com/mpeters›? [y/N]: y
sh-5.1$
```
but why doesn't it tell me whether it was allowed or not? It's just silent.
