### ISSUE TITLE
webhooks from gitlab freedesktop cannot be ingested

### ISSUE THREAD

**Issue by TomasTomecek** [packit/packit-service#1696]
```
[Wed Oct 12 13:59:07.653036 2022] [wsgi:error] [pid 360:tid 372] [remote 10.131.2.7:54220] 2022-10-12 13:59:07.652 webhooks.py INFO X-Gitlab-Token not in request.headers
[Wed Oct 12 13:59:07.660821 2022] [wsgi:error] [pid 360:tid 372] [remote 10.131.2.7:54220] Authentication for url 'https://gitlab.freedesktop.org/polkit/polkit' is missing in the config.
[Wed Oct 12 13:59:07.662055 2022] [wsgi:error] [pid 360:tid 372] [remote 10.131.2.7:54220] 2022-10-12 13:59:07.661 app.py ERROR Exception on /api/webhooks/gitlab [POST]
[Wed Oct 12 13:59:07.662068 2022] [wsgi:error] [pid 360:tid 372] [remote 10.131.2.7:54220] Traceback (most recent call last):
[Wed Oct 12 13:59:07.662071 2022] [wsgi:error] [pid 360:tid 372] [remote 10.131.2.7:54220] File "/usr/lib/python3.10/site-packages/packit/config/config.py", line 217, in _get_project
[Wed Oct 12 13:59:07.662074 2022] [wsgi:error] [pid 360:tid 372] [remote 10.131.2.7:54220] project = get_project(
[Wed Oct 12 13:59:07.662077 2022] [wsgi:error] [pid 360:tid 372] [remote 10.131.2.7:54220] File "/usr/lib/python3.10/site-packages/ogr/factory.py", line 103, in get_project
[Wed Oct 12 13:59:07.662079 2022] [wsgi:error] [pid 360:tid 372] [remote 10.131.2.7:54220] raise OgrException(
[Wed Oct 12 13:59:07.662082 2022] [wsgi:error] [pid 360:tid 372] [remote 10.131.2.7:54220] ogr.exceptions.OgrException: Instance of type GitlabService matching instance url 'https://gitlab.freedesktop.org/polkit/polkit' was not provided.
[Wed Oct 12 13:59:07.662084 2022] [wsgi:error] [pid 360:tid 372] [remote 10.131.2.7:54220]
[Wed Oct 12 13:59:07.662087 2022] [wsgi:error] [pid 360:tid 372] [remote 10.131.2.7:54220] During handling of the above exception, another exception occurred:
[Wed Oct 12 13:59:07.662089 2022] [wsgi:error] [pid 360:tid 372] [remote 10.131.2.7:54220]
[Wed Oct 12 13:59:07.662091 2022] [wsgi:error] [pid 360:tid 372] [remote 10.131.2.7:54220] Traceback (most recent call last):
[Wed Oct 12 13:59:07.662094 2022] [wsgi:error] [pid 360:tid 372] [remote 10.131.2.7:54220] File "/usr/lib/python3.10/site-packages/flask/app.py", line 1513, in full_dispatch_request
[Wed Oct 12 13:59:07.662096 2022] [wsgi:error] [pid 360:tid 372] [remote 10.131.2.7:54220] rv = self.dispatch_request()
[Wed Oct 12 13:59:07.662099 2022] [wsgi:error] [pid 360:tid 372] [remote 10.131.2.7:54220] File "/usr/lib/python3.10/site-packages/flask/app.py", line 1499, in dispatch_request
[Wed Oct 12 13:59:07.662101 2022] [wsgi:error] [pid 360:tid 372] [remote 10.131.2.7:54220] return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
[Wed Oct 12 13:59:07.662103 2022] [wsgi:error] [pid 360:tid 372] [remote 10.131.2.7:54220] File "/usr/lib/python3.10/site-packages/flask_restx/api.py", line 403, in wrapper
[Wed Oct 12 13:59:07.662106 2022] [wsgi:error] [pid 360:tid 372] [remote 10.131.2.7:54220] resp = resource(*args, **kwargs)
[Wed Oct 12 13:59:07.662108 2022] [wsgi:error] [pid 360:tid 372] [remote 10.131.2.7:54220] File "/usr/lib/python3.10/site-packages/flask/views.py", line 83, in view
[Wed Oct 12 13:59:07.662110 2022] [wsgi:error] [pid 360:tid 372] [remote 10.131.2.7:54220] return self.dispatch_request(*args, **kwargs)
[Wed Oct 12 13:59:07.662113 2022] [wsgi:error] [pid 360:tid 372] [remote 10.131.2.7:54220] File "/usr/lib/python3.10/site-packages/flask_restx/resource.py", line 49, in dispatch_request
[Wed Oct 12 13:59:07.662115 2022] [wsgi:error] [pid 360:tid 372] [remote 10.131.2.7:54220] resp = meth(*args, **kwargs)
[Wed Oct 12 13:59:07.662118 2022] [wsgi:error] [pid 360:tid 372] [remote 10.131.2.7:54220] File "/src/packit_service/service/api/webhooks.py", line 186, in post
[Wed Oct 12 13:59:07.662120 2022] [wsgi:error] [pid 360:tid 372] [remote 10.131.2.7:54220] self.validate_token()
[Wed Oct 12 13:59:07.662122 2022] [wsgi:error] [pid 360:tid 372] [remote 10.131.2.7:54220] File "/src/packit_service/service/api/webhooks.py", line 271, in validate_token
[Wed Oct 12 13:59:07.662125 2022] [wsgi:error] [pid 360:tid 372] [remote 10.131.2.7:54220] self.create_confidential_issue_with_token()
[Wed Oct 12 13:59:07.662127 2022] [wsgi:error] [pid 360:tid 372] [remote 10.131.2.7:54220] File "/src/packit_service/service/api/webhooks.py", line 230, in create_confidential_issue_with_token
[Wed Oct 12 13:59:07.662130 2022] [wsgi:error] [pid 360:tid 372] [remote 10.131.2.7:54220] packit_user = project.service.user.get_username()
[Wed Oct 12 13:59:07.662132 2022] [wsgi:error] [pid 360:tid 372] [remote 10.131.2.7:54220] File "/usr/lib/python3.10/site-packages/packit/config/config.py", line 223, in _get_project
[Wed Oct 12 13:59:07.662135 2022] [wsgi:error] [pid 360:tid 372] [remote 10.131.2.7:54220] raise PackitConfigException(msg, ex)
[Wed Oct 12 13:59:07.662138 2022] [wsgi:error] [pid 360:tid 372] [remote 10.131.2.7:54220] packit.exceptions.PackitConfigException: ("Authentication for url 'https://gitlab.freedesktop.org/polkit/polkit' is missing in the config.", OgrException("Instance of type GitlabService matching instance url 'https://gitlab.freedesktop.org/polkit/polkit' was not provided."))
10.131.2.7 - - [12/Oct/2022:13:59:07 +0000] "POST /api/webhooks/gitlab HTTP/1.1" 500 37
```

The URL matching code doesn't work :/

TODO:
- [ ] fix this :)
- [ ] ping jrybar on internal IRC once this is available on stg

**Comment by mfocko** [comment]
It does work… Just the token was gone from the config, I would love to know why, cause it is in the vault and also I remember updating the config on the running production :)

**Comment by mfocko** [comment]
AFAIK this only affected production, which I fixed moments ago (updated secret and rescaled everything). Stage seems to have the correct version of the config.

My guesses:
- redeploying without synced configs
- OpenShift being unreliable with updates of secrets on-the-go

**Comment by TomasTomecek** [comment]
oh wow! Thanks for checking this b/c I looked into packit-service.yaml config in BW and was puzzled because all the data were there; @lachmanfrantisek also said that it *should* work
