### ISSUE TITLE
armhfp builds failing with KeyError

### ISSUE THREAD

**Issue by osandov** [packit/packit-service#1790]
Hello,

fedora-35-armhfp and fedora-36-armhfp builds of my project (https://github.com/osandov/drgn) are failing with the following error:

```
Running (timeout=18000): unbuffer mock --buildsrpm --spec /var/lib/copr-rpmbuild/workspace/workdir-9exr658r/python-drgn/python-drgn.spec --sources /var/lib/copr-rpmbuild/workspace/workdir-9exr658r/python-drgn --resultdir /var/lib/copr-rpmbuild/results --uniqueext 1669774145.803942 -r /var/lib/copr-rpmbuild/results/configs/child.cfg
INFO: Unable to build arch armv7hl natively on arch x86_64. Setting forcearch to use software emulation.
ERROR: 'armv7hl'
Traceback (most recent call last):
  File "/usr/libexec/mock/mock", line 1065, in <module>
    exitStatus = main()
                 ^^^^^^
  File "/usr/lib/python3.11/site-packages/mockbuild/trace_decorator.py", line 93, in trace
    result = func(*args, **kw)
             ^^^^^^^^^^^^^^^^^
  File "/usr/libexec/mock/mock", line 687, in main
    check_arch_combination(config_opts['rpmbuild_arch'], config_opts)
  File "/usr/lib/python3.11/site-packages/mockbuild/trace_decorator.py", line 93, in trace
    result = func(*args, **kw)
             ^^^^^^^^^^^^^^^^^
  File "/usr/libexec/mock/mock", line 532, in check_arch_combination
    binary = f'/usr/bin/qemu-{config_opts["qemu_user_static_mapping"][config_opts["forcearch"]]}-static'
                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'armv7hl'
ERROR: 'armv7hl'
Traceback (most recent call last):
  File "/usr/libexec/mock/mock", line 1065, in <module>
    exitStatus = main()
                 ^^^^^^
  File "/usr/lib/python3.11/site-packages/mockbuild/trace_decorator.py", line 93, in trace
    result = func(*args, **kw)
             ^^^^^^^^^^^^^^^^^
  File "/usr/libexec/mock/mock", line 687, in main
    check_arch_combination(config_opts['rpmbuild_arch'], config_opts)
  File "/usr/lib/python3.11/site-packages/mockbuild/trace_decorator.py", line 93, in trace
    result = func(*args, **kw)
             ^^^^^^^^^^^^^^^^^
  File "/usr/libexec/mock/mock", line 532, in check_arch_combination
    binary = f'/usr/bin/qemu-{config_opts["qemu_user_static_mapping"][config_opts["forcearch"]]}-static'
                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'armv7hl'
Copr build error: Mock build failed
```

See https://dashboard.packit.dev/results/copr-builds/542859 and https://dashboard.packit.dev/results/copr-builds/542864 for a couple of examples.

Is this a known issue? Is it related to arm32 being deprecated in Fedora?

Thanks!

**Comment by TomasTomecek** [comment]
Hi, thank you for opening this issue!

I forwarded it to the Copr team who handles the actual building. Let's see their response.

**Comment by TomasTomecek** [comment]
ping @FrostyX @praiskup @nikromen

**Comment by lachmanfrantisek** [comment]
Thanks @FrostyX! I'm going to close this issue then.

**Comment by osandov** [comment]
My builds are passing again. Thanks everyone.
