### ISSUE TITLE
Sentry reporting tracebacks in pod logs with `AttributeError: '_Code' object has no attribute 'co_positions'`

### ISSUE THREAD

**Issue by TomasTomecek** [packit/packit-service#1872]
When I opened logs after workers froze on Tue around 11:00, I saw a swarm of these tracebacks:
```
[2023-01-31 09:22:12,014: WARNING/MainProcess] --- Logging error ---
[2023-01-31 09:22:12,015: WARNING/MainProcess] Traceback (most recent call last):
[2023-01-31 09:22:12,015: WARNING/MainProcess]   File "/usr/lib/python3.11/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2023-01-31 09:22:12,016: WARNING/MainProcess]   File "/usr/lib/python3.11/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
[2023-01-31 09:22:12,016: WARNING/MainProcess]   File "/usr/lib/python3.11/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
[2023-01-31 09:22:12,016: WARNING/MainProcess]   File "/usr/local/lib64/python3.11/site-packages/gevent/_socketcommon.py", line 607, in connect
    raise _SocketError(err, strerror(err))
[2023-01-31 09:22:12,016: WARNING/MainProcess] ConnectionRefusedError: [Errno 111] Connection refused
[2023-01-31 09:22:12,016: WARNING/MainProcess] 
During handling of the above exception, another exception occurred:
[2023-01-31 09:22:12,016: WARNING/MainProcess] Traceback (most recent call last):
[2023-01-31 09:22:12,016: WARNING/MainProcess]   File "/usr/lib/python3.11/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
[2023-01-31 09:22:12,016: WARNING/MainProcess]   File "/usr/lib/python3.11/site-packages/urllib3/connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
[2023-01-31 09:22:12,016: WARNING/MainProcess]   File "/usr/lib/python3.11/site-packages/urllib3/connection.py", line 239, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
[2023-01-31 09:22:12,017: WARNING/MainProcess]   File "/usr/lib64/python3.11/http/client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
[2023-01-31 09:22:12,017: WARNING/MainProcess]   File "/usr/lib64/python3.11/http/client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
[2023-01-31 09:22:12,017: WARNING/MainProcess]   File "/usr/lib64/python3.11/http/client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
[2023-01-31 09:22:12,017: WARNING/MainProcess]   File "/usr/lib64/python3.11/http/client.py", line 1037, in _send_output
    self.send(msg)
[2023-01-31 09:22:12,017: WARNING/MainProcess]   File "/usr/lib64/python3.11/http/client.py", line 975, in send
    self.connect()
[2023-01-31 09:22:12,017: WARNING/MainProcess]   File "/usr/lib/python3.11/site-packages/urllib3/connection.py", line 205, in connect
    conn = self._new_conn()
           ^^^^^^^^^^^^^^^^
[2023-01-31 09:22:12,017: WARNING/MainProcess]   File "/usr/lib/python3.11/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
[2023-01-31 09:22:12,017: WARNING/MainProcess] urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fb41f551690>: Failed to establish a new connection: [Errno 111] Connection refused
[2023-01-31 09:22:12,017: WARNING/MainProcess] 
During handling of the above exception, another exception occurred:
[2023-01-31 09:22:12,017: WARNING/MainProcess] Traceback (most recent call last):
[2023-01-31 09:22:12,017: WARNING/MainProcess]   File "/usr/lib/python3.11/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
[2023-01-31 09:22:12,018: WARNING/MainProcess]   File "/usr/lib/python3.11/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
[2023-01-31 09:22:12,018: WARNING/MainProcess]   File "/usr/lib/python3.11/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
[2023-01-31 09:22:12,018: WARNING/MainProcess] urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='tokman', port=80): Max retries exceeded with url: /api/oamg/leapp-repository (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb41f551690>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2023-01-31 09:22:12,018: WARNING/MainProcess] 
During handling of the above exception, another exception occurred:
[2023-01-31 09:22:12,018: WARNING/MainProcess] Traceback (most recent call last):
[2023-01-31 09:22:12,018: WARNING/MainProcess]   File "/usr/lib/python3.11/site-packages/ogr/abstract.py", line 108, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
[2023-01-31 09:22:12,018: WARNING/MainProcess]   File "/usr/lib/python3.11/site-packages/ogr/services/github/service.py", line 186, in get_pygithub_instance
    token = self.authentication.get_token(namespace, repo)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2023-01-31 09:22:12,018: WARNING/MainProcess]   File "/usr/lib/python3.11/site-packages/ogr/services/github/auth_providers/tokman.py", line 32, in get_token
    response = requests.get(f"{self._instance_url}/api/{namespace}/{repo}")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2023-01-31 09:22:12,019: WARNING/MainProcess]   File "/usr/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2023-01-31 09:22:12,019: WARNING/MainProcess]   File "/usr/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2023-01-31 09:22:12,019: WARNING/MainProcess]   File "/usr/lib/python3.11/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2023-01-31 09:22:12,019: WARNING/MainProcess]   File "/usr/lib/python3.11/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2023-01-31 09:22:12,019: WARNING/MainProcess]   File "/usr/lib/python3.11/site-packages/requests/adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
[2023-01-31 09:22:12,019: WARNING/MainProcess] requests.exceptions.ConnectionError: HTTPConnectionPool(host='tokman', port=80): Max retries exceeded with url: /api/oamg/leapp-repository (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb41f551690>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2023-01-31 09:22:12,019: WARNING/MainProcess] 
The above exception was the direct cause of the following exception:
[2023-01-31 09:22:12,019: WARNING/MainProcess] Traceback (most recent call last):
[2023-01-31 09:22:12,019: WARNING/MainProcess]   File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 451, in trace_task
    R = retval = fun(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^
[2023-01-31 09:22:12,019: WARNING/MainProcess]   File "/usr/local/lib/python3.11/site-packages/sentry_sdk/integrations/celery.py", line 207, in _inner
    reraise(*exc_info)
[2023-01-31 09:22:12,020: WARNING/MainProcess]   File "/usr/local/lib/python3.11/site-packages/sentry_sdk/_compat.py", line 60, in reraise
    raise value
[2023-01-31 09:22:12,020: WARNING/MainProcess]   File "/usr/local/lib/python3.11/site-packages/sentry_sdk/integrations/celery.py", line 202, in _inner
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
[2023-01-31 09:22:12,020: WARNING/MainProcess]   File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 734, in __protected_call__
    return self.run(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
[2023-01-31 09:22:12,020: WARNING/MainProcess]   File "/usr/local/lib/python3.11/site-packages/packit_service/worker/tasks.py", line 143, in process_message
    return SteveJobs().process_message(event=event)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2023-01-31 09:22:12,020: WARNING/MainProcess]   File "/usr/local/lib/python3.11/site-packages/packit_service/worker/jobs.py", line 144, in process_message
    return SteveJobs(event_object).process()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2023-01-31 09:22:12,020: WARNING/MainProcess]   File "/usr/local/lib/python3.11/site-packages/packit_service/worker/jobs.py", line 156, in process
    if not self.is_project_public_or_enabled_private():
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2023-01-31 09:22:12,020: WARNING/MainProcess]   File "/usr/local/lib/python3.11/site-packages/packit_service/worker/jobs.py", line 494, in is_project_public_or_enabled_private
    elif self.event.project.is_private():
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2023-01-31 09:22:12,020: WARNING/MainProcess]   File "/usr/lib/python3.11/site-packages/ogr/abstract.py", line 108, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
[2023-01-31 09:22:12,020: WARNING/MainProcess]   File "/usr/lib/python3.11/site-packages/ogr/services/github/project.py", line 138, in is_private
    return self.github_repo.private
           ^^^^^^^^^^^^^^^^
[2023-01-31 09:22:12,020: WARNING/MainProcess]   File "/usr/lib/python3.11/site-packages/ogr/services/github/project.py", line 82, in github_repo
    self._github_repo = self.github_instance.get_repo(
                        ^^^^^^^^^^^^^^^^^^^^
[2023-01-31 09:22:12,020: WARNING/MainProcess]   File "/usr/lib/python3.11/site-packages/ogr/services/github/project.py", line 73, in github_instance
    self._github_instance = self.service.get_pygithub_instance(
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2023-01-31 09:22:12,020: WARNING/MainProcess]   File "/usr/lib/python3.11/site-packages/ogr/abstract.py", line 114, in wrapper
    raise OgrNetworkError(
[2023-01-31 09:22:12,020: WARNING/MainProcess] ogr.exceptions.OgrNetworkError: Could not perform the request due to a network error
[2023-01-31 09:22:12,020: WARNING/MainProcess] 
During handling of the above exception, another exception occurred:
[2023-01-31 09:22:12,020: WARNING/MainProcess] Traceback (most recent call last):
[2023-01-31 09:22:12,021: WARNING/MainProcess]   File "/usr/lib64/python3.11/logging/handlers.py", line 987, in emit
    msg = self.format(record)
          ^^^^^^^^^^^^^^^^^^^
[2023-01-31 09:22:12,021: WARNING/MainProcess]   File "/usr/lib64/python3.11/logging/__init__.py", line 953, in format
    return fmt.format(record)
           ^^^^^^^^^^^^^^^^^^
[2023-01-31 09:22:12,021: WARNING/MainProcess]   File "/usr/local/lib/python3.11/site-packages/syslog_rfc5424_formatter/__init__.py", line 154, in format
    return header + super(RFC5424Formatter, self).format(record)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2023-01-31 09:22:12,021: WARNING/MainProcess]   File "/usr/lib64/python3.11/logging/__init__.py", line 695, in format
    record.exc_text = self.formatException(record.exc_info)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2023-01-31 09:22:12,021: WARNING/MainProcess]   File "/usr/lib64/python3.11/logging/__init__.py", line 645, in formatException
    traceback.print_exception(ei[0], ei[1], tb, None, sio)
[2023-01-31 09:22:12,021: WARNING/MainProcess]   File "/usr/lib64/python3.11/traceback.py", line 124, in print_exception
    te = TracebackException(type(value), value, tb, limit=limit, compact=True)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2023-01-31 09:22:12,021: WARNING/MainProcess]   File "/usr/lib64/python3.11/traceback.py", line 690, in __init__
    self.stack = StackSummary._extract_from_extended_frame_gen(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2023-01-31 09:22:12,021: WARNING/MainProcess]   File "/usr/lib64/python3.11/traceback.py", line 416, in _extract_from_extended_frame_gen
    for f, (lineno, end_lineno, colno, end_colno) in frame_gen:
[2023-01-31 09:22:12,021: WARNING/MainProcess]   File "/usr/lib64/python3.11/traceback.py", line 353, in _walk_tb_with_full_positions
    positions = _get_code_position(tb.tb_frame.f_code, tb.tb_lasti)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2023-01-31 09:22:12,021: WARNING/MainProcess]   File "/usr/lib64/python3.11/traceback.py", line 366, in _get_code_position
    positions_gen = code.co_positions()
                    ^^^^^^^^^^^^^^^^^
[2023-01-31 09:22:12,021: WARNING/MainProcess] AttributeError: '_Code' object has no attribute 'co_positions'
[2023-01-31 09:22:12,021: WARNING/MainProcess] Call stack:
[2023-01-31 09:22:12,022: WARNING/MainProcess]   File "/usr/local/lib/python3.11/site-packages/celery/concurrency/base.py", line 29, in apply_target
    ret = target(*args, **kwargs)
[2023-01-31 09:22:12,022: WARNING/MainProcess]   File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 649, in fast_trace_task
    R, I, T, Rstr = tasks[task].__trace__(
[2023-01-31 09:22:12,022: WARNING/MainProcess]   File "/usr/local/lib/python3.11/site-packages/sentry_sdk/integrations/celery.py", line 184, in _inner
    return f(*args, **kwargs)
[2023-01-31 09:22:12,022: WARNING/MainProcess]   File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 468, in trace_task
    I, R, state, retval = on_error(task_request, exc, uuid)
[2023-01-31 09:22:12,022: WARNING/MainProcess]   File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 379, in on_error
    R = I.handle_error_state(
[2023-01-31 09:22:12,022: WARNING/MainProcess]   File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 178, in handle_error_state
    return {
[2023-01-31 09:22:12,022: WARNING/MainProcess]   File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 237, in handle_failure
    self._log_error(task, req, einfo)
[2023-01-31 09:22:12,022: WARNING/MainProcess]   File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 265, in _log_error
    logger.log(policy.severity, policy.format.strip(), context,
[2023-01-31 09:22:12,022: WARNING/MainProcess]   File "/usr/lib64/python3.11/logging/__init__.py", line 1559, in log
    self._log(level, msg, args, **kwargs)
[2023-01-31 09:22:12,022: WARNING/MainProcess]   File "/usr/lib64/python3.11/logging/__init__.py", line 1634, in _log
    self.handle(record)
[2023-01-31 09:22:12,022: WARNING/MainProcess]   File "/usr/lib64/python3.11/logging/__init__.py", line 1644, in handle
    self.callHandlers(record)
[2023-01-31 09:22:12,022: WARNING/MainProcess]   File "/usr/local/lib/python3.11/site-packages/sentry_sdk/integrations/logging.py", line 96, in sentry_patched_callhandlers
    return old_callhandlers(self, record)
[2023-01-31 09:22:12,023: WARNING/MainProcess] Message: 'Task %(name)s[%(id)s] %(description)s: %(exc)s'
```

the exceptions varied: tokman, ogr.exceptions.OgrNetworkError: Could not perform the request due to a network error (github)

there was about a few dozens of exceptions

it's really hard to tell what went wrong

**Comment by lbarcziova** [comment]
We are hitting this more and more often and should investigate it.

**Comment by nforro** [comment]
Celery 5.3.0b2 has been in Fedora 37 for a while now: https://bodhi.fedoraproject.org/updates/FEDORA-2023-7bdc7aa5d, so I don't think the last comment in that issue is valid.

**Comment by mfocko** [comment]
@nforro Could be old `billiard`? They mentioned 4.1.0 (https://github.com/celery/billiard/issues/377#issuecomment-1458444870)

**Comment by mfocko** [comment]
Ha! we install it via pip /o\

**Comment by mfocko** [comment]
Isn't the issue that we have pinned older Celery release that depends on the older billiard?

**Comment by nforro** [comment]
Yes, I think that's what Jirka meant, backporting the "fix" to older billiard installed from pip. I think we could just fork billiard, backport the commit and pip-install from the fork.

**Comment by jpopelka** [comment]
> I think we could just fork billiard, backport the commit and pip-install from the fork.

nice :+1:
