### ISSUE TITLE
column "job_trigger_id" of relation "srpm_builds" does not exist

### ISSUE THREAD

**Issue by jpopelka** [packit/packit-service#778]
from prod workers:

```
Task TaskName.pr_comment_copr_build[d87ab396-017e-49bc-b784-a0ee42677974] raised unexpected: ProgrammingError('(psycopg2.ProgrammingError) column "job_trigger_id" of relation "srpm_builds" does not exist\nLINE 1: INSERT INTO srpm_builds (logs, success, job_trigger_id) VALU...\n                                                ^\n')
Traceback (most recent call last):
  File "/usr/lib64/python3.7/site-packages/sqlalchemy/engine/base.py", line 1278, in _execute_context
    cursor, statement, parameters, context
  File "/usr/lib64/python3.7/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
psycopg2.ProgrammingError: column "job_trigger_id" of relation "srpm_builds" does not exist
LINE 1: INSERT INTO srpm_builds (logs, success, job_trigger_id) VALU...
                                                ^
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 650, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/sentry_sdk/integrations/celery.py", line 171, in _inner
    reraise(*exc_info)
  File "/usr/local/lib/python3.7/site-packages/sentry_sdk/_compat.py", line 57, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/sentry_sdk/integrations/celery.py", line 166, in _inner
    return f(*args, **kwargs)
  File "/src/packit_service/worker/tasks.py", line 166, in run_pr_comment_copr_build_handler
    return get_handlers_task_results(handler.run_job(), event)
  File "/src/packit_service/worker/handlers/abstract.py", line 253, in run_job
    job_results[result_key] = self.run_n_clean()
  File "/src/packit_service/worker/handlers/abstract.py", line 152, in run_n_clean
    return self.run()
  File "/src/packit_service/worker/handlers/github_handlers.py", line 574, in run
    handler_results = cbh.run_copr_build()
  File "/src/packit_service/worker/build/copr_build.py", line 167, in run_copr_build
    self.create_srpm_if_needed()
  File "/src/packit_service/worker/build/build_helper.py", line 303, in create_srpm_if_needed
    self._create_srpm()
  File "/src/packit_service/worker/build/build_helper.py", line 364, in _create_srpm
    logs=srpm_logs, success=srpm_success, trigger_model=self.db_trigger,
  File "/src/packit_service/models.py", line 942, in create
    return srpm_build
  File "/usr/lib64/python3.7/contextlib.py", line 119, in __exit__
    next(self.gen)
  File "/src/packit_service/models.py", line 80, in get_sa_session
    session.commit()
  File "/usr/lib64/python3.7/site-packages/sqlalchemy/orm/session.py", line 1042, in commit
    self.transaction.commit()
  File "/usr/lib64/python3.7/site-packages/sqlalchemy/orm/session.py", line 504, in commit
    self._prepare_impl()
  File "/usr/lib64/python3.7/site-packages/sqlalchemy/orm/session.py", line 483, in _prepare_impl
    self.session.flush()
  File "/usr/lib64/python3.7/site-packages/sqlalchemy/orm/session.py", line 2523, in flush
    self._flush(objects)
  File "/usr/lib64/python3.7/site-packages/sqlalchemy/orm/session.py", line 2664, in _flush
    transaction.rollback(_capture_exception=True)
  File "/usr/lib64/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__
    exc_value, with_traceback=exc_tb,
  File "/usr/lib64/python3.7/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/usr/lib64/python3.7/site-packages/sqlalchemy/orm/session.py", line 2624, in _flush
    flush_context.execute()
  File "/usr/lib64/python3.7/site-packages/sqlalchemy/orm/unitofwork.py", line 422, in execute
    rec.execute(self)
  File "/usr/lib64/python3.7/site-packages/sqlalchemy/orm/unitofwork.py", line 589, in execute
    uow,
  File "/usr/lib64/python3.7/site-packages/sqlalchemy/orm/persistence.py", line 245, in save_obj
    insert,
  File "/usr/lib64/python3.7/site-packages/sqlalchemy/orm/persistence.py", line 1136, in _emit_insert_statements
    statement, params
  File "/usr/lib64/python3.7/site-packages/sqlalchemy/engine/base.py", line 1014, in execute
    return meth(self, multiparams, params)
  File "/usr/lib64/python3.7/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/lib64/python3.7/site-packages/sqlalchemy/engine/base.py", line 1133, in _execute_clauseelement
    distilled_params,
  File "/usr/lib64/python3.7/site-packages/sqlalchemy/engine/base.py", line 1318, in _execute_context
    e, statement, parameters, cursor, context
  File "/usr/lib64/python3.7/site-packages/sqlalchemy/engine/base.py", line 1512, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/usr/lib64/python3.7/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/usr/lib64/python3.7/site-packages/sqlalchemy/engine/base.py", line 1278, in _execute_context
    cursor, statement, parameters, context
  File "/usr/lib64/python3.7/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) column "job_trigger_id" of relation "srpm_builds" does not exist
LINE 1: INSERT INTO srpm_builds (logs, success, job_trigger_id) VALU...
                                                ^

[SQL: INSERT INTO srpm_builds (logs, success, job_trigger_id) VALUES (%(logs)s, %(success)s, %(job_trigger_id)s) RETURNING srpm_builds.id]
[parameters: {'logs': '05:31:51.691 local_project.py  DEBUG  Arguments received in the init method of the LocalProject class: \ngit_repo: None\nworking_dir: /sandcastle\nre ... (4069 characters truncated) ... EBUG  The `rpmbuild` command output: setting SOURCE_DATE_EPOCH=1597622400\nWrote: ./hello-0.74-1.20200817053328533092.pr108.1.g458c300.fc31.src.rpm\n', 'success': True, 'job_trigger_id': 5419}]
(Background on this error at: http://sqlalche.me/e/13/f405 )
```

**Comment by jpopelka** [comment]
Looks like #768 , any ideas @IceWreck ?

**Comment by jpopelka** [comment]
from packit-service logs:
```
+ source /src/setup_env_in_openshift.sh
++ set -x
++ export PACKIT_HOME=/home/packit
++ PACKIT_HOME=/home/packit
++ grep -v '^packit' /etc/passwd
+++ id -u
++ printf 'packit:x:1012120000:0:Packit Service:/home/packit:/bin/bash\n'
++ export LD_PRELOAD=libnss_wrapper.so
++ LD_PRELOAD=libnss_wrapper.so
++ export NSS_WRAPPER_PASSWD=/home/packit/passwd
++ NSS_WRAPPER_PASSWD=/home/packit/passwd
++ export NSS_WRAPPER_GROUP=/etc/group
++ NSS_WRAPPER_GROUP=/etc/group
+ pushd /src
+ n=0
+ '[' 0 -ge 7 ']'
+ alembic upgrade head
/src /
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade adbdc1c21d7e -> 726cb0f70c6d, link srpmbuildmodel to jobtriggermodel
/usr/bin/run_httpd.sh: line 16:     9 Killed                  alembic upgrade head
+ n=1
+ sleep 2
+ '[' 1 -ge 7 ']'
+ alembic upgrade head
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade adbdc1c21d7e -> 726cb0f70c6d, link srpmbuildmodel to jobtriggermodel
/usr/bin/run_httpd.sh: line 16:    14 Killed                  alembic upgrade head
+ n=2
+ sleep 2
+ '[' 2 -ge 7 ']'
+ alembic upgrade head
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade adbdc1c21d7e -> 726cb0f70c6d, link srpmbuildmodel to jobtriggermodel
/usr/bin/run_httpd.sh: line 16:    19 Killed                  alembic upgrade head
+ n=3
+ sleep 2
+ '[' 3 -ge 7 ']'
+ alembic upgrade head
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade adbdc1c21d7e -> 726cb0f70c6d, link srpmbuildmodel to jobtriggermodel
/usr/bin/run_httpd.sh: line 16:    24 Killed                  alembic upgrade head
+ n=4
+ sleep 2
+ '[' 4 -ge 7 ']'
+ alembic upgrade head
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade adbdc1c21d7e -> 726cb0f70c6d, link srpmbuildmodel to jobtriggermodel
/usr/bin/run_httpd.sh: line 16:    29 Killed                  alembic upgrade head
+ n=5
+ sleep 2
+ '[' 5 -ge 7 ']'
+ alembic upgrade head
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade adbdc1c21d7e -> 726cb0f70c6d, link srpmbuildmodel to jobtriggermodel
/usr/bin/run_httpd.sh: line 16:    34 Killed                  alembic upgrade head
+ n=6
+ sleep 2
+ '[' 6 -ge 7 ']'
+ alembic upgrade head
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade adbdc1c21d7e -> 726cb0f70c6d, link srpmbuildmodel to jobtriggermodel
/usr/bin/run_httpd.sh: line 16:    39 Killed                  alembic upgrade head
+ n=7
+ sleep 2
+ '[' 7 -ge 7 ']'
+ popd
/
+ httpd -DFOREGROUND
```

**Comment by jpopelka** [comment]
Checking packit-service@stg logs, the latest started OK 4 days ago:
```
+ pushd /src
+ n=0
+ '[' 0 -ge 7 ']'
+ alembic upgrade head
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
+ break
+ popd
+ httpd -DFOREGROUND
/
```

**Comment by IceWreck** [comment]
Working on it.

**Comment by IceWreck** [comment]
@jpopelka does this happen during the migration or while running something.

**Comment by jpopelka** [comment]
It's happening only on prod during migration. Also when I go to the packit-service pod's Terminal and type 'alembic upgrade head' I get `Killed` so it looks like it's oomkilled, but even when I increased the mem limit to 196Mi (previously was 128) I still see it. Unfortunatelly we don't have `strace` in the image to debug that.

**Comment by jpopelka** [comment]
Fixed by temporarily increasing packit-service pod memory limit.

Updated docs: https://github.com/packit/deployment/pull/122
