### ISSUE TITLE
parsing TFT results in a traceback

### ISSUE THREAD

**Issue by TomasTomecek** [packit/packit-service#967]
```
Traceback (most recent call last):                                                                                                                                                            
  File "/usr/lib/python3.9/site-packages/celery/app/trace.py", line 405, in trace_task                                                                                                        
    R = retval = fun(*args, **kwargs)                                                                                                                                                         
  File "/usr/lib/python3.9/site-packages/celery/app/trace.py", line 697, in __protected_call__                                                                                                
    return self.run(*args, **kwargs)                                                                                                                                                          
  File "/usr/local/lib/python3.9/site-packages/sentry_sdk/integrations/celery.py", line 197, in _inner                                                                                        
    reraise(*exc_info)                                                                                                                                                                          File "/usr/local/lib/python3.9/site-packages/sentry_sdk/_compat.py", line 54, in reraise                                                                                                        raise value                                                                                                                                                                                 File "/usr/local/lib/python3.9/site-packages/sentry_sdk/integrations/celery.py", line 192, in _inner                                                                                            return f(*args, **kwargs)                                                                                                                                                                 
  File "/src/packit_service/worker/tasks.py", line 98, in process_message                                                                                                                     
    return SteveJobs().process_message(event=event, topic=topic, source=source)                                                                                                               
  File "/src/packit_service/worker/jobs.py", line 332, in process_message                                                                                                                     
    event_object = Parser.parse_event(event)                                                                                                                                                  
  File "/src/packit_service/worker/parser.py", line 113, in parse_event                                                                                                                       
    for response in map(                                                                                                                                                                      
  File "/src/packit_service/worker/parser.py", line 114, in <lambda>                                                                                                                          
    lambda parser: parser(event),                                                                                                                                                             
  File "/src/packit_service/worker/parser.py", line 778, in parse_testing_farm_results_event                                                                                                  
    tests: List[TestResult] = Parser._parse_tf_result_xunit(                                                                                                                                  
  File "/src/packit_service/worker/parser.py", line 738, in _parse_tf_result_xunit                                                                                                            
    return [                                                                                                                                                                                  
  File "/src/packit_service/worker/parser.py", line 740, in <listcomp>                                                                                                                        
    name=testcase["@name"],                                                                                                                                                                   
TypeError: string indices must be integers   
```

not sure if this is known

**Comment by jpopelka** [comment]
Trying to reproduce it in our worker:prod image, but with no luck.
```python
In [19]: xunit="<testsuites overall-result=\"failed\"><properties/><testsuite overall-result=\"failed\" tests=\"1\"><properties><property name=\"baseosci.overall-result\" value=\"FAILED\"/></properties><testcase name=\"/script-00\" result
    ...: =\"failed\"><properties><property name=\"baseosci.arch\" value=\"x86_64\"/><property name=\"baseosci.connectable_host\" value=\"172.31.31.163\"/><property name=\"baseosci.distro\" value=\"CentOS-8\"/><property name=\"baseosci.sta
    ...: tus\" value=\"Complete\"/><property name=\"baseosci.testcase.source.url\" value=\"\"/><property name=\"baseosci.variant\" value=\"\"/></properties><logs><log href=\"http://artifacts.dev.testing-farm.io/a86acc59-0f5f-44a5-b24d-7e5
    ...: 10471be94/work-unittestsQYXaXa/plans/unittests/execute/data/script-00\" name=\"log_dir\"/><log href=\"http://artifacts.dev.testing-farm.io/a86acc59-0f5f-44a5-b24d-7e510471be94/work-unittestsQYXaXa/plans/unittests/execute/data/scr
    ...: ipt-00/output.txt\" name=\"testout.log\"/></logs><failure/><testing-environment name=\"requested\"><property name=\"arch\" value=\"x86_64\"/><property name=\"compose\" value=\"CentOS-8\"/><property name=\"snapshots\" value=\"Fals
    ...: e\"/></testing-environment><testing-environment name=\"provisioned\"><property name=\"arch\" value=\"x86_64\"/><property name=\"compose\" value=\"CentOS-8\"/><property name=\"snapshots\" value=\"False\"/></testing-environment></t
    ...: estcase></testsuite></testsuites>"                                                                                                                                                                                                   

In [20]: xmltodict.parse(xunit)                                                                                                                                                                                                               
Out[20]: 
OrderedDict([('testsuites',
              OrderedDict([('@overall-result', 'failed'),
                           ('properties', None),
                           ('testsuite',
                            OrderedDict([('@overall-result', 'failed'),
                                         ('@tests', '1'),
                                         ('properties',
                                          OrderedDict([('property',
                                                        OrderedDict([('@name',
                                                                      'baseosci.overall-result'),
                                                                     ('@value',
                                                                      'FAILED')]))])),
                                         ('testcase',
                                          OrderedDict([('@name', '/script-00'),
                                                       ('@result', 'failed'),
                                                       ('properties',
                                                        OrderedDict([('property',
                                                                      [OrderedDict([('@name',
                                                                                     'baseosci.arch'),
                                                                                    ('@value',
                                                                                     'x86_64')]),
                                                                       OrderedDict([('@name',
                                                                                     'baseosci.connectable_host'),
                                                                                    ('@value',
                                                                                     '172.31.31.163')]),
                                                                       OrderedDict([('@name',
                                                                                     'baseosci.distro'),
                                                                                    ('@value',
                                                                                     'CentOS-8')]),
                                                                       OrderedDict([('@name',
                                                                                     'baseosci.status'),
                                                                                    ('@value',
                                                                                     'Complete')]),
                                                                       OrderedDict([('@name',
                                                                                     'baseosci.testcase.source.url'),
                                                                                    ('@value',
                                                                                     '')]),
                                                                       OrderedDict([('@name',
                                                                                     'baseosci.variant'),
                                                                                    ('@value',
                                                                                     '')])])])),
                                                       ('logs',
                                                        OrderedDict([('log',
                                                                      [OrderedDict([('@href',
                                                                                     'http://artifacts.dev.testing-farm.io/a86acc59-0f5f-44a5-b24d-7e510471be94/work-unittestsQYXaXa/plans/unittests/execute/data/script-00'),
                                                                                    ('@name',
                                                                                     'log_dir')]),
                                                                       OrderedDict([('@href',
                                                                                     'http://artifacts.dev.testing-farm.io/a86acc59-0f5f-44a5-b24d-7e510471be94/work-unittestsQYXaXa/plans/unittests/execute/data/script-00/output.txt'),
                                                                                    ('@name',
                                                                                     'testout.log')])])])),
                                                       ('failure', None),
                                                       ('testing-environment',
                                                        [OrderedDict([('@name',
                                                                       'requested'),
                                                                      ('property',
                                                                       [OrderedDict([('@name',
                                                                                      'arch'),
                                                                                     ('@value',
                                                                                      'x86_64')]),
                                                                        OrderedDict([('@name',
                                                                                      'compose'),
                                                                                     ('@value',
                                                                                      'CentOS-8')]),
                                                                        OrderedDict([('@name',
                                                                                      'snapshots'),
                                                                                     ('@value',
                                                                                      'False')])])]),
                                                         OrderedDict([('@name',
                                                                       'provisioned'),
                                                                      ('property',
                                                                       [OrderedDict([('@name',
                                                                                      'arch'),
                                                                                     ('@value',
                                                                                      'x86_64')]),
                                                                        OrderedDict([('@name',
                                                                                      'compose'),
                                                                                     ('@value',
                                                                                      'CentOS-8')]),
                                                                        OrderedDict([('@name',
                                                                                      'snapshots'),
                                                                                     ('@value',
                                                                                      'False')])])])])]))]))]))])
```
while in the linked sentry issue, it was parsed into 
```
{testsuites: 
  {@overall-result: 'failed',
   properties: None, testsuite:
    {@overall-result: 'failed',
     @tests: '1', properties: {"property":"OrderedDict([('@name', 'baseosci.overall-result'), ('@value', 'FAILED')])"},
     testcase:
      {"@name":"'/script-00'",
       "@result":"'failed'",
       "failure":"None","logs":"OrderedDict([('log', [OrderedDict([('@href', ...
```
i.e. some values in the dict are not `OrderedDict` and some string values (like `"'/script-00'"`) are enclosed in another pair of apostrophes.

I'll keep an eye on it, but I can't properly fix it if I'm not able to reproduce.

**Comment by TomasTomecek** [comment]
> /me hides, sneaks through window out and runs as hell

maybe it was a flake and Miro deployed a new version in the meantime - yep, let's keep this open and close in 2/4 weeks

**Comment by jpopelka** [comment]
It's not about what came from TF, but how we parsed (well, tried to parse) it.
Ok, let's give it some time to see more occurrences.

**Comment by jpopelka** [comment]
I see lots of these in Sentry. I tried again to reproduce in `worker:prod`, but no luck.
Hence #988

**Comment by jpopelka** [comment]
We have workaround #988 in place. Closing
